### DAV  Lab3

 ## Question-1

In [1]:
import numpy as np

In [ ]:
a=np.random.randint(2,50,(3,4))
print(a)
mean=np.mean(a)
median=np.median(a)
std=np.std(a)
sum=np.sum(a)
sum1=np.sum(a,axis=1)
b=a.reshape((2,6))
print("Mean is",mean)
print("Median is",median)
print("Standard Deviation is",std)
print("Sum of all elements is",sum)
print("Sum of each row is",sum1)
print(b)

[[26 36 21 31]
 [22 27  9 25]
 [ 8 27 29 38]]
Mean is 24.916666666666668
Median is 26.5
Standard Deviation is 8.760311384623012
Sum of all elements is 299
Sum of each row is [114  83 102]
[[26 36 21 31 22 27]
 [ 9 25  8 27 29 38]]


### Question-2

In [17]:
import numpy as np

c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[10,11,12],[13,14,15],[16,17,18]])

add = c + d
sub = c - d
mul = c * d
dot_prod = np.dot(c, d)

trans_c = c.T
trans_d = d.T

det_c = np.linalg.det(c)
det_d = np.linalg.det(d)

print("Sum is\n", add)
print("Difference is\n", sub)
print("Product is\n", mul)
print("Dot product is\n", dot_prod)
print("Transpose of c is\n", trans_c)
print("Transpose of d is\n", trans_d)
print("Det of c is", det_c)
print("Det of d is", det_d)

# Inverse check
if det_c != 0:
    print("Inverse of c is\n", np.linalg.inv(c))
else:
    print("Inverse of c does not exist (det = 0)")

if det_d != 0:
    print("Inverse of d is\n", np.linalg.inv(d))
else:
    print("Inverse of d does not exist")


Sum is
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Difference is
 [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
Product is
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
Dot product is
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Transpose of c is
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of d is
 [[10 13 16]
 [11 14 17]
 [12 15 18]]
Det of c is -9.51619735392994e-16
Det of d is 0.0
Inverse of c is
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Inverse of d does not exist
