In [1]:
import numpy as np

In [5]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [7]:
np.ones((4,2,2))


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [11]:
# array with randoms
np.random.rand(4,2)


array([[0.33731637, 0.92016155],
       [0.40001821, 0.77810997],
       [0.71295946, 0.4918963 ],
       [0.73716188, 0.23305152]])

In [13]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [14]:
np.random.random_sample(a.shape)

array([[[0.73940122, 0.87069443],
        [0.99781053, 0.12894528]],

       [[0.30757633, 0.12791298],
        [0.24562848, 0.44435949]]])

In [23]:
# random integers
np.random.randint(7,size=(3,4))

array([[5, 2, 5, 1],
       [2, 2, 3, 4],
       [4, 4, 1, 0]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
a=np.array([1,2,3])
b=a
b

array([1, 2, 3])