### Mathematics

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a+2

array([3, 4, 5, 6])

In [5]:
a-2

array([-1,  0,  1,  2])

In [6]:
a*2


array([2, 4, 6, 8])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [9]:
a**2

array([ 1,  4,  9, 16])

In [10]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra

In [11]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [12]:
# determinant
c=np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [13]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.min(stats)

1

In [15]:
np.max(stats,axis=1)

array([3, 6])

In [16]:
np.sum(stats,axis=0)

array([5, 7, 9])