### Accessing/changing specific elements, row, columns, etc

In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
a[1,5]

13

In [7]:
# get a specific row

In [8]:
a[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
#get a specific column
a[:,0]

array([1, 8])

In [13]:
# getting a little more fancy 
a[0,1:6:2]

array([2, 4, 6])

In [14]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
a[1,2]=5
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


### 3D Example

In [16]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
b[:,0,0]

array([1, 5])

In [18]:
# rep;acing in 3D
b[:,1,:]=9
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]
