### Numpy

In [4]:
import numpy as np

## The Basics

In [6]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
a.dtype

dtype('int64')

In [16]:
# Get item size (in bytes)
a.itemsize

8

In [19]:
a.size
a.nbytes

24

In [18]:
b.size

6