### Reorganising Arrays

In [1]:
import numpy as np


In [4]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [5]:
# vertically stacking vectors
v1=np.array([1,2,3,4,5])
v2=np.array([6,7,8,9,10])
np.vstack([v1,v2,v1,v2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
# horizantal stacks
np.hstack([v1,v2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
k=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(k)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
mul=k.prod()
print(mul)

362880
